import struct
import ffxi_sql as s
import os


def calcWikiaUrl(itemName):
    pass

def calcBGUrl(itemName):
    pass

#WIKIA_ROOT = 'http://ffxiclopedia.wikia.com/wiki/'
#BG_ROOT = 'http://www.bg-wiki.com/bg/'


supportSession = s.cnnf()

q= supportSession.query(s.baseItems).all()
items = {}
items[0] = 'No Item'
for item in q:
    items[item.rowid] = item.itemNameEnglish
q = supportSession.query(s.zoneId).all()
zones = {}
zoneByName = {}
for zone in q:
    zones[zone.rowid] = zone.__repr__()
    
#q = None

#def Formula(stats):
#    pass


    #Pre-randomizer pDIF Caps by weapon type
    #Type	non-crit	crit
    #H2H	3.5	4.5
    #1H	3.25	4.25
    #2H	3.75	4.75
    #Marksmanship	3.5	3.5*1.25
    #Archery and Thrown	3.25	3.25*1.25
# notes, /check mob, high defense > 1.0 ration, low defense < 1.25
# level correction ratio (cRatio) (level + ilvl), only applicable in some zones-- test & DB it!

#Melee attacks have 0.05/level ratio penalty
#cRatio = Ratio - (target's level - attacker's level) × 0.05
#Ranged attacks have 0.025/level ratio penalty
#cRatio = Ratio - (target's level - attacker's level) × 0.025
        #wRatio
        #1. Calculate wRatio using your cRatio
        #If you critical hit: wRatio = (cRatio + 1)
        #If you do not critical hit: wRatio = (cRatio + 0)

#Optional: You can represent this mathematically write this using a logical expression, 
#which will be 1 when true and 0 when false. Rand represents a random number from 0 to 1.

#wRatio = cRatio + ( Rand < CritRate% )
#ex: If your critical hit rate is 25% (0.25) and Rand (A random number between 0-1) is 0.1, the equation becomes wRatio = cRatio + 1

# calculate pDIF to generate ratio, (ratio)(weapon damage)(randomizer 1.0-1.05) == real damage 

#return {[0] = {id=0,en="Inventory",access="Everywhere",command="inventory",equippable=true},
#    [1] = {id=1,en="Safe",access="Mog House",command="bank",equippable=false},
#    [2] = {id=2,en="Storage",access="Mog House",command="storage",equippable=false},
#    [3] = {id=3,en="Temporary",access="Situational",command="temporary",equippable=false},
#    [4] = {id=4,en="Locker",access="Mog House",command="locker",equippable=false},
#    [5] = {id=5,en="Satchel",access="Everywhere",command="satchel",equippable=false},
#    [6] = {id=6,en="Sack",access="Everywhere",command="sack",equippable=false},
#    [7] = {id=7,en="Case",access="Everywhere",command="case",equippable=false},
#    [8] = {id=8,en="Wardrobe",access="Everywhere",command="wardrobe",equippable=true},
#    [9] = {id=9,en="Safe 2",access="Mog House",command="bank2",equippable=false},
#    [10] = {id=10,en="Wardrobe 2",access="Everywhere",command="wardrobe2",equippable=true},
#    [11] = {id=11,en="Wardrobe 3",access="Everywhere",command="wardrobe3",equippable=true},
#    [12] = {id=12,en="Wardrobe 4",access="Everywhere",command="wardrobe4",equippable=true},
#}, {"id", "en", "access", "command", "equippable"}

AhIType = {     0x02:'Open Menu Response',
                0x03:'Unknown logout',
                0x04:'Sell Item Confirmation',
                0x05:'Open Sales Status Menu',
                0x0a:'Open Menu Confirmation',
                0x0B:'Sell Item Confirmation',
                0x0d:'Sales Item Status',
                0x0e:'Unknown type added 09-03-18'    }


AhSaleStat= {   0x00:'-',
                0x02:'Placing',
                0x03:'On Auction',
                0x0a:'Sold',
                0x0b:'Not Sold',
                0x10:'Checking'     }


bags = {    0:'Inventory',
            1:'Safe',
            2:'Storage',
            3:'Temporary',
            4:'Locker',
            5:'Satchel',
            6:'Sack',
            7:'Case',
            8:'Wardrobe',
            9:'Safe2',
            10:'Wardrobe2',
            11:'Wardrobe3',
            12:'Wardrobe4'  }

itemFlags = {   0x0000:'None',
                0x000a:'WallHanging',
                0x0002:'Flag1',
                0x0004:'Flag2',
                0x0008:'Flag3',
                0x0010:'DeliveryInner',
                0x0020:'Inscribable',
                0x0040:'NoAuction',  
                0x0080:'Scroll',
                0x0100:'Linkshell',
                0x0200:'CanUse',
                0x0400:'CanTradeNPC',
                0x0800:'CanEquip',
                0x1000:'NoSale',
                0x2000:'NoDelivery', 
                0x4000:'NoTrade', 
                0x8000:'Rare',
                0x6040:'Exclusive'}

itemstat = {    0x00:'None',
                0x01:'Unknown 0x01',
                0x02:'Unknown 0x02',
                0x03:'Unknown 0x03',
                0x04:'Unknown 0x04',
                0x05 : 'Equipped',
                0x06:'Unknown 0x06',
                0x07:'Unknown 0x07',
                0x08:'Unknown 0x08',
                0x09:'Unknown 0x09',
                0x0a:'Unknown 0x0a',
                0x0b:'Unknown 0x0b',
                0x0c:'Unknown 0x0c',
                0x0d:'Unknown 0x0d',
                0x0e:'Unknown 0x0e',
                0x0F : 'Synthing',
                0x10:'Unknown 0x10',
                0x11:'Unknown 0x11',
                0x12:'Unknown 0x12',
                0x13 : 'Active linkshell',
                0x14:'Unknown 0x14',
                0x15:'Unknown 0x15',
                0x16:'Unknown 0x16',
                0x19 : 'Bazaaring'  }

jobs = {    0:'None',
            1:'War',
            2:'Mnk',
            3:'Whm',
            4:'Blm',
            5:'Rdm',
            6:'Thf',
            7:'Pld',
            8:'Drk',
            9:'Bst',
            10:'Brd',
            11:'Rng',
            12:'Sam',
            13:'Nin',
            14:'Drg',
            15:'Smn',
            16:'Blu',
            17:'Cor',
            18:'Pup',
            19:'Dnc',
            20:'Sch',
            21:'Geo',
            22:'Run',
            23:'Mon'}

stats = {   0:'STR',
            1:'DEX',
            2:'VIT',
            3:'AGI',
            4:'INT',
            5:'MND',
            6:'CHR'}


indi = {
    0x5F:'Enemy Dark',
    0x5E:'Enemy Light',
    0x5D:'Enemy Water',
    0x5C:'Enemy Lightning',
    0x5B:'Enemy Earth',
    0x5A:'Enemy Wind',
    0x59:'Enemy Ice',
    0x58:'Enemy Fire',
    0x57:'Party Dark',
    0x56:'Party Light',
    0x55:'Party Water',
    0x54:'Party Lightning',
    0x53:'Party Earth',
    0x52:'Party Wind',
    0x51:'Party Ice',
    0x50:'Party Fire',
    0x00:'None',
}

chatMode = {    0:'Say',
                1:'Shout',
                3:'Tell',
                4:'Party',
                5:'Linkshell',
                8:'Emote',
                26:'Yell',
                27:'Linkshell2',
                33:'Unity'  }

KI_Categories = {   0:'Temporary Key Items',
                    1:'Permanent Key Items',
                    2:'Voidwatch',
                    3:'Maps',
                    4:'ActiveEffects',
                    5:'Claim Slips',
                    6:'Abyssea',
                    7:'MogGarden',
                    8:'Gaes Fete',
                    9:'Mounts' }

#enums.quest_mission_log = {
#    [0x0030] = 'Completed Campaign Missions',
#    [0x0038] = 'Completed Campaign Missions (2)',       -- Starts at index 256
#    [0x0050] = 'Current San d\'Oria Quests',
#    [0x0058] = 'Current Bastok Quests',
#    [0x0060] = 'Current Windurst Quests',
#    [0x0068] = 'Current Jeuno Quests',
#    [0x0070] = 'Current Other Quests',
#    [0x0078] = 'Current Outlands Quests',
#    [0x0080] = 'Current TOAU Quests and Missions (TOAU, WOTG, Assault, Campaign)',
#    [0x0088] = 'Current WOTG Quests',
#    [0x0090] = 'Completed San d\'Oria Quests',
#    [0x0098] = 'Completed Bastok Quests',
#    [0x00A0] = 'Completed Windurst Quests',
#    [0x00A8] = 'Completed Jeuno Quests',
#    [0x00B0] = 'Completed Other Quests',
#    [0x00B8] = 'Completed Outlands Quests',
#    [0x00C0] = 'Completed TOAU Quests and Assaults',
#    [0x00C8] = 'Completed WOTG Quests',
#    [0x00D0] = 'Completed Missions (Nations, Zilart)',
#    [0x00D8] = 'Completed Missions (TOAU, WOTG)',
#    [0x00E0] = 'Current Abyssea Quests',
#    [0x00E8] = 'Completed Abyssea Quests',
#    [0x00F0] = 'Current Adoulin Quests',
#    [0x00F8] = 'Completed Adoulin Quests',
#    [0x0100] = 'Current Coalition Quests', 
#    [0x0108] = 'Completed Coalition Quests', 
#    [0xFFFF] = 'Current Missions',               
#}



## AH  sales status
#enums['sale stat'] = {
#    [0x00] = '-',
#    [0x02] = 'Placing',
#    [0x03] = 'On auction',
#    [0x0A] = 'Sold',
#    [0x0B] = 'Not sold',
#    [0x10] = 'Checking',
#}




#delivery box types for  0x04b
#enums.delivery = {
#    -- Seems to occur when refreshing the d-box after any change (or before changes).
#    [0x01] = 'Slot info',
#    -- Seems to occur when placing items into the d-box.
#    [0x02] = 'Place item',
#    -- Two occur per item that is actually sent (hitting "OK" to send).
#    [0x03] = 'Send confirm',
#    -- Two occur per sent item that is Canceled.
#    [0x04] = 'Send cancel',
#    -- Seems to occur quasi-randomly. Can be seen following spells.
#    [0x05] = 'Unknown 0x05',
#    -- Occurs for new items.
#    -- Two of these are sent sequentially. The first one doesn't seem to contain much/any
#    -- information and the second one is very similar to a type 0x01 packet
#    -- First packet's frst line:   4B 58 xx xx 06 01 00 01 FF FF FF FF 02 02 FF FF
#    -- Second packet's first line: 4B 58 xx xx 06 01 00 FF FF FF FF FF 01 02 FF FF
#    [0x06] = 'New item',
#    -- Occurs as the first packet when removing something from the send box.
#    [0x07] = 'Remove item (send)',
#    -- Occurs as the first packet when removing or dropping something from the delivery box.
#    [0x08] = 'Remove/drop item (delivery)',
#    -- Occurs when someone returns something from the delivery box.
#    [0x09] = 'Return item',
#    -- Occurs as the second packet when removing something from the delivery box or send box.
#    [0x0A] = 'Remove item confirm',
#    -- Occurs as the second packet when dropping something from the delivery box.
#    [0x0B] = 'Drop item (delivery)',
#    -- Sent after entering a name and hitting "OK" in the outbox.
#    [0x0C] = 'Send request',
#    -- Sent after requesting the send box, causes the client to open the send box dialogue.
#    [0x0D] = 'Send dialogue start',
#    -- Sent after requesting the delivery box, causes the client to open the delivery box dialogue.
#    [0x0E] = 'Delivery dialogue start',
#    -- Sent after closing the delivery box or send box.
#    [0x0F] = 'Delivery/send dialogue finish',
#}


# spawn types for in 0x5b
#enums.spawntype = {
#    [0x03] = 'Monster',
#    [0x00] = 'Casket or NPC',
#    [0x0A] = 'Self',
#}


#1278 east lovejoy

Elements = {    0:'None',
                1:'Fire',
                2:'Wind',
                3:'Lightning',
                4:'Light',
                5:'Ice',
                6:'Earth',
                7:'Water',
                8:'Dark'
}

OutgoingAction = {  0x00:'NPC Interaction',
                    0x02:'Engage Monster',
                    0x03:'Magic Cast',
                    0x04:'Disengage',
                    0x05:'Call for help',
                    0x07:'Weaponskill Usage',
                    0x09:'Job Ability Usage',
                    0x0c:'Assist',
                    0x0d:'Reraise Dialogue',
                    0x0e:'Cast Fishing Rod',
                    0x0f:'Switch Target',
                    0x10:'Ranged Attack',
                    0x12:'Dismount Chocobo',
                    0x14:'Zoning/Appear',
                    0x19:'Monsterskill',
                    0x1a:'Mount'    }

DeliveryTypes = {   0x01:'Slot Info',
                    0x02:'Place item',
                    0x03:'Send confirm',
                    0x04:'Send cancel',
                    0x05:'Unknown (0x05)',
                    0x06:'New Item',
                    0x07:'Remove Item(send)',
                    0x08:'Remove/drop item (Delivery)',
                    0x09:'Return Item',
                    0x0a:'Remove Item(confirm)',
                    0x0b:'Drop Item (Delivery)',
                    0x0c:'Send Request',
                    0x0d:'Send Dialogue Start',
                    0x0e:'Receive Dialogue Start',
                    0x0f:'Delivery/Send Dialogue Finish'}

#Combat skills
#return {
#    [0] = {id=0,en="(N/A)",ja="(N/A)",category="None"},
#    [1] = {id=1,en="Hand-to-Hand",ja="格闘",category="Combat"},
#    [2] = {id=2,en="Dagger",ja="短剣",category="Combat"},
#    [3] = {id=3,en="Sword",ja="片手剣",category="Combat"},
#    [4] = {id=4,en="Great Sword",ja="両手剣",category="Combat"},
#    [5] = {id=5,en="Axe",ja="片手斧",category="Combat"},
#    [6] = {id=6,en="Great Axe",ja="両手斧",category="Combat"},
#    [7] = {id=7,en="Scythe",ja="両手鎌",category="Combat"},

#    [8] = {id=8,en="Polearm",ja="両手槍",category="Combat"},
#    [9] = {id=9,en="Katana",ja="片手刀",category="Combat"},
#    [10] = {id=10,en="Great Katana",ja="両手刀",category="Combat"},
#    [11] = {id=11,en="Club",ja="片手棍",category="Combat"},
#    [12] = {id=12,en="Staff",ja="両手棍",category="Combat"},

#    [22] = {id=22,en="Automaton Melee",ja="白兵戦",category="Puppet"},
#    [23] = {id=23,en="Automaton Archery",ja="射撃戦",category="Puppet"},
#    [24] = {id=24,en="Automaton Magic",ja="魔法戦",category="Puppet"},

#    [25] = {id=25,en="Archery",ja="弓術",category="Combat"},
#    [26] = {id=26,en="Marksmanship",ja="射撃",category="Combat"},
#    [27] = {id=27,en="Throwing",ja="投てき",category="Combat"},
#    [28] = {id=28,en="Guard",ja="ガード",category="Combat"},
#    [29] = {id=29,en="Evasion",ja="回避",category="Combat"},
#    [30] = {id=30,en="Shield",ja="盾",category="Combat"},
#    [31] = {id=31,en="Parrying",ja="受け流し",category="Combat"},

#    [32] = {id=32,en="Divine Magic",ja="神聖魔法",category="Magic"},
#    [33] = {id=33,en="Healing Magic",ja="回復魔法",category="Magic"},
#    [34] = {id=34,en="Enhancing Magic",ja="強化魔法",category="Magic"},
#    [35] = {id=35,en="Enfeebling Magic",ja="弱体魔法",category="Magic"},
#    [36] = {id=36,en="Elemental Magic",ja="精霊魔法",category="Magic"},
#    [37] = {id=37,en="Dark Magic",ja="暗黒魔法",category="Magic"},
#    [38] = {id=38,en="Summoning Magic",ja="召喚魔法",category="Magic"},
#    [39] = {id=39,en="Ninjutsu",ja="忍術",category="Magic"},
#    [40] = {id=40,en="Singing",ja="歌唱",category="Magic"},
#    [41] = {id=41,en="Stringed Instrument",ja="弦楽器",category="Magic"},
#    [42] = {id=42,en="Wind Instrument",ja="管楽器",category="Magic"},
#    [43] = {id=43,en="Blue Magic",ja="青魔法",category="Magic"},
#    [44] = {id=44,en="Geomancy",ja="風水魔法",category="Magic"},
#    [45] = {id=45,en="Handbell",ja="風水鈴",category="Magic"},

#    [46]
#   [47]

# Craft skills
#    [48] = {id=48,en="Fishing",ja="釣り",category="Synthesis"},
#    [49] = {id=49,en="Woodworking",ja="木工",category="Synthesis"},
#    [50] = {id=50,en="Smithing",ja="鍛冶",category="Synthesis"},
#    [51] = {id=51,en="Goldsmithing",ja="彫金",category="Synthesis"},
#    [52] = {id=52,en="Clothcraft",ja="裁縫",category="Synthesis"},
#    [53] = {id=53,en="Leathercraft",ja="革細工",category="Synthesis"},
#    [54] = {id=54,en="Bonecraft",ja="骨細工",category="Synthesis"},
#    [55] = {id=55,en="Alchemy",ja="錬金術",category="Synthesis"},
#    [56] = {id=56,en="Cooking",ja="調理",category="Synthesis"},
#    [57] = {id=57,en="Synergy",ja="錬成",category="Synthesis"},
#}, {"id", "en", "ja", "category"}


#types.equipset_build = L{
#    {ctype='boolbit',           label='Active'},                                -- 00
#    {ctype='bit',               label='_unknown1'},                             -- 00
#    {ctype='bit[6]',            label='Bag',                fn=bag},            -- 00
#    {ctype='unsigned char',     label='Inventory Index'},                       -- 01
#    {ctype='unsigned short',    label='Item',               fn=item},           -- 02
#}

#-- Equip set

equipSlot = { 0:'Main',
                1:'Sub',
                2:'Range',
                3:'Ammo',
                4:'Head',
                5:'Neck',
                6:'Ear1',
                7:'Ear2',
                8:'Body',
                9:'Hands',
                10:'Ring1',
                11:'Ring2',
                12:'Back',
                13:'Waist',
                14:'Legs',
                15:'Feet'   }

messages = { 1 : "$'actor' hits $'target' for $'number' points of damage.",
    2 : "$'actor' casts $'spell'.$'lb'$'target' takes $'number' points of damage.",
    3 : "$'actor' starts casting $'spell'.",
    4 : "$'target' is out of range.",
    5 : "Unable to see $'target'.",
    6 : "$'actor' defeats $'target'.",
    7 : "$'actor' casts $'spell'.$'lb'$'target' recovers $'number' HP.",
    8 : "$'actor' gains $'number' experience points.",
    9 : "$'actor' attains level $'number'!",
    10 :"$'actor' loses $'number' experience points.",
    11 :"$'actor' falls to level $'number'.",
    12 :"Cannot attack.$'lb'Your target is already claimed.",
    13 :"Debug Message: $'actor': $'target' is now invincible.",
    14 :"$'actor''s attack is countered by $'target'.$'lb'$'number' of $'actor''s shadows absorbs the damage and disappears.",
    15 :"$'actor' misses $'target'.",
    16 :"$'actor''s casting is interrupted.",
    17 :"Unable to cast spells at this time.",
    18 :"Unable to cast spells at this time.",
    19 :"$'actor' calls for help!",
    20 :"$'target' falls to the ground.",
    21 :"No experience points gained.",
    22 :"You cannot call for help at this time.",
    23 :"$'actor' learns a new spell!",
    24 :"$'target' recovers $'number' HP.",
    25 :"$'target' recovers $'number' MP.",
    26 :"$'target' recovers $'number' HP and MP.",
    27 :"Debug Message: Cannot execute command.$'lb'No (BTCALC) command in ATEL source.",
    28 :"$'actor' uses a $'item'.",
    29 :"$'actor' is paralyzed.",
    30 :"$'target' anticipates the attack.",
    31 :"$'number' of $'target''s shadows absorbs the damage and disappears.",
    32 :"$'target' dodges the attack.",
    33 :"$'actor''s attack is countered by $'target'.$'lb'$'actor' takes $'number' points of damage.",
    34 :"$'actor' does not have enough MP to cast $'spell'.",
    35 :"$'actor' lacks the ninja tools to cast $'spell'.",
    36 :"You lose sight of $'target'.",
    37 :"You are too far from the battle to gain experience.",
    38 :"$'target''s $'skill' skill rises 0.$'number2' points.",
    39 :"You need the Dual Wield ability to equip the $'item' as a sub-weapon.",
    40 :"You cannot use $'spell' in this area.",
    41 :"$'actor': Status ailment check ($'number')Cannot rest at this time.",
    42 :"$'actor' casts $'spell' on $'target'.",
    43 :"$'actor' readies $'weapon_skill'.",
    44 :"$'target''s spikes deal $'number' points of damage to $'actor'.",
    45 :"$'actor' learns \"$'weapon_skill'\"!",
    46 :"Debug Message: Current POP number: ($'number')",
    47 :"$'actor' cannot cast $'spell'.",
    48 :"$'spell' cannot be cast on $'target'.",
    49 :"$'actor' is unable to cast spells.",
    50 :"$'actor' earns a merit points!$'lb'(Total: $'number')",
    51 :"--Out of sight--",
    52 :"$'target' gives up chasing $'actor'.$'lb'---Find Path Error---",
    53 :"$'target''s $'skill' skill reaches level $'number2'.",
    54 :"$'actor' gains $'number' Besieged points.",
    55 :"Unable to use item.",
    56 :"Unable to use item.",
    57 :"Job changed.",
    58 :"Invalid job number.",
    59 :"You do not have access to specified job yet.",
    60 :"You do not have access to support jobs yet.",
    61 :"You cannot have the same job as both main and support jobs.",
    62 :"The $'item' fails to activate.",
    63 :"$'actor' misses $'target'.",
    64 :"$'target' is no longer $'status'.",
    65 :"You are not carrying any Petras.$'lb'You cannot use the $'item'.",
    66 :"Debug: Resisted spell!",
    67 :"$'actor' scores a critical hit!$'lb'$'target' takes $'number' points of damage.",
    68 :"Debug: Casting interrupted!",
    69 :"$'target' blocks $'actor''s attack with his shield.",
    70 :"$'target' parries $'actor''s attack with his weapon.",
    71 :"$'actor' cannot perform that action.",
    72 :"That action cannot be performed on $'target'.",
    73 :"Debug: $'target''s status is now $'status'.",
    74 :"Debug: $'target' recovers from $'status'.",
    75 :"$'actor''s $'spell' has no effect on $'target'.",
    76 :"No valid target within area of effect.",
    77 :"$'actor' uses Sange.$'lb'$'target' takes $'number' points of damage.",
    78 :"$'target' is too far away.",
    79 :"Debug: $'target' uses Double Attack($'number'%).",
    80 :"Debug: $'target' uses Triple Attack($'number'%).",
    81 :"Debug: Battle Debug No.$'lb'($'number') used on $'target'.",
    82 :"$'actor' casts $'spell'.$'lb'$'target' is $'status'!",
    83 :"$'actor' casts $'spell'.$'lb'$'actor' successfully removes $'target''s $'status'.",
    84 :"$'actor' is paralyzed.",
    85 :"$'actor' casts $'spell'.$'lb'$'target' resists the spell.",
    86 :"$'actor' casts $'spell', but $'target' is outside the area of effect.",
    87 :"Unable to use job ability.",
    88 :"Unable to use job ability.",
    89 :"Unable to use weapon skill.",
    90 :"Unable to use weapon skill.",
    91 :"$'actor' does not have any $'item'.",
    92 :"Cannot use the $'item' on $'target'.",
    93 :"$'actor' casts $'spell'.$'lb'$'target' vanishes.",
    94 :"You must wait longer to perform that action.",
    95 :"You cannot learn $'spell'.$'lb'You do not meet the job or level requirements.",
    96 :"You already know $'spell'.",
    97 :"$'target' was defeated by $'actor'.",
    98 :"You obtain a $'item' from $'target'.",
    99 :"$'actor''$'target': $'number', $'number'",
    100 :"$'actor' uses $'ability'.",
    101 :"$'actor' uses $'weapon_skill'.",
    102 :"$'actor' uses $'ability'.$'lb'$'target' recovers $'number' HP.",
    103 :"$'actor' uses $'weapon_skill'.$'lb'$'target' recovers $'number' HP.",
    104 :"Unable to use item.$'lb'You do not meet the level requirement.",
    105 :"$'actor' gains $'number' experience points.",
    106 :"$'actor' is intimidated by $'target''s presence.",
    107 :"$'target' is temporarily unable to access support job abilities.",
    108 :"$'actor' uses $'ability'.$'lb'Pet's powers increase!",
    109 :"$'actor' uses $'weapon_skill'.$'lb'Pet's powers increase!",
    110 :"$'actor' uses $'ability'.$'lb'$'target' takes $'number' points of damage.",
    111 :"You cannot use $'item' while medicated.",
    112 :"$'target''s doom counter is now down to $'number'.",
    113 :"$'actor' casts $'spell'.$'lb'$'target' falls to the ground.",
    114 :"$'actor' casts $'spell' on $'target', but the spell fails to take effect.",
    115 :"$'actor' uses $'ability'.$'lb'Attacks are enhanced but defense weakens.",
    116 :"$'actor' uses $'ability'.$'lb'$'target''s attacks are enhanced.",
    117 :"$'actor' uses $'ability'.$'lb'Defense is enhanced but attacks weaken.",
    118 :"$'actor' uses $'ability'.$'lb'Accuracy is enhanced but evasion is impaired.",
    119 :"$'actor' uses $'ability' on $'target'.",
    120 :"$'actor' uses $'ability'.$'lb'$'target''s accuracy is enhanced.",
    121 :"$'actor' uses $'ability'.$'lb'$'target''s evasion is enhanced.",
    122 :"$'actor' uses $'ability'.$'lb'$'actor' recovers $'number' HP.",
    123 :"$'actor' uses $'ability'.$'lb'$'actor' successfully removes $'target''s $'status'.",
    124 :"$'actor' achieves Gate Breach status!",
    125 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.",
    126 :"$'actor' uses $'ability'.$'lb'$'actor''s movement speed increases.",
    127 :"$'actor' uses $'ability'.$'lb'$'target' is $'status'.",
    128 :"$'target' is $'status' and cannot perform that action.",
    129 :"$'actor' uses $'ability'.$'lb'$'actor' mugs $'number' from $'target'.",
    130 :"$'target' is $'status' for making a equipment change.",
    131 :"$'actor' uses $'ability'.$'lb'$'target' is fortified against undead.",
    132 :"$'target''s spikes drain $'number' HP from $'actor'.",
    133 :"$'actor' uses $'ability'.$'lb'$'actor' steals $'number' Petra from $'target'.",
    134 :"$'actor' uses $'ability'.$'lb'$'target' is fortified against arcana.",
    135 :"$'actor' uses $'weapon_skill' on $'target'.",
    136 :"$'actor' uses $'ability'.$'lb'$'target' is now under $'actor''s control.",
    137 :"$'actor' uses $'ability'.$'lb'$'actor' fails to charm $'target'.",
    138 :"$'actor' uses $'ability'.$'lb'$'target' seems friendlier.",
    139 :"$'actor' uses $'ability', but finds nothing.",
    140 :"$'actor' uses $'ability', and finds a $'item2'.",
    141 :"$'actor' uses $'ability'.$'lb'$'target' is $'status'.",
    142 :"$'actor' uses $'weapon_skill'.$'lb'$'target' receives the effect of Accuracy Down and Evasion Down.",
    143 :"$'actor' uses $'ability'.$'lb'Ranged attacks become more accurate.",
    144 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Accuracy Down and Evasion Down.",
    145 :"$'target' receives the effect of Accuracy Down and Evasion Down.",
    146 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Accuracy Boost and Evasion Boost.",
    147 :"$'target' receives the effect of Accuracy Boost and Evasion Boost.",
    148 :"$'actor' uses $'ability'.$'lb'$'target' is fortified against demons.",
    149 :"$'target' is fortified against demons.",
    150 :"$'actor' uses $'ability'.$'lb'$'target' is fortified against dragons.",
    151 :"$'target' is fortified against dragons.",
    152 :"Additional effect: $'actor' recovers $'number' MP.",
    153 :"$'actor' uses $'ability'.$'lb'$'actor' fails to steal from $'target'.",
    154 :"$'target' is out of range.",
    155 :"You cannot perform that action on the specified target.",
    156 :"$'actor' uses $'ability'.$'lb'No effect on $'target'.",
    157 :"$'actor' uses Barrage.$'lb'$'target' takes $'number' points of damage.",
    158 :"$'actor' uses $'ability', but misses.",
    159 :"$'actor' uses $'weapon_skill'.$'lb'$'target''s $'status' effect disappears!",
    160 :"Additional effect: $'status'.",
    161 :"Additional effect: $'number' HP drained from $'target'.",
    162 :"Additional effect: $'number' MP drained from $'target'.",
    163 :"Additional effect: $'number' points of damage.",
    164 :"Additional effect: $'status'.",
    165 :"Additional effect: $'number' TP drained from $'target'.",
    166 :"Additional effect: $'actor' gains the effect of $'status'.",
    167 :"Additional effect: $'actor' recovers $'number' HP.",
    168 :"Additional effect: $'target''s $'status' effect disappears!",
    169 :"Additional effect: Warp!",
    170 :"$'target' seems $'skill'.$'lb'It seems to have high evasion and defense.",
    171 :"$'target' seems $'skill'.$'lb'It seems to have high evasion.",
    172 :"$'target' seems $'skill'.$'lb'It seems to have high evasion but low defense.",
    173 :"$'target' seems $'skill'.$'lb'It seems to have high defense.",
    174 :"$'target' seems $'skill'.",
    175 :"$'target' seems $'skill'.$'lb'It seems to have low defense.",
    176 :"$'target' seems $'skill'.$'lb'It seems to have low evasion but high defense.",
    177 :"$'target' seems $'skill'.$'lb'It seems to have low evasion.",
    178 :"$'target' seems $'skill'.$'lb'It seems to have low evasion and defense.",
    179 :"$'target': hit-eva($'number') :' $'number'%",
    180 :"str-vit($'number') dmg-adj($'number')",
    181 :"atk-def($'number') ofs-adj%($'number')",
    182 :"$'target': MonNo($'number')-Lev($'number')",
    183 :"HIT-EVA($'number') ATK-DEF($'number')",
    184 :"$'actor':ALLIANCE SUM:$'number'/LEV:$'number'",
    185 :"$'actor' uses $'weapon_skill'.$'lb'$'target' takes $'number' points of damage.",
    186 :"$'actor' uses $'weapon_skill'.$'lb'$'target' gains the effect of $'status'.",
    187 :"$'actor' uses $'weapon_skill'.$'lb'$'number' HP drained from $'target'.",
    188 :"$'actor' uses $'weapon_skill', but misses $'target'.",
    189 :"$'actor' uses $'weapon_skill'.$'lb'No effect on $'target'.",
    190 :"$'actor' cannot use that weapon ability.",
    191 :"$'actor' is unable to use weapon skills.",
    192 :"$'actor' does not have enough TP.",
    193 :"$'weapon_skill' cannot be used against that target.",
    194 :"$'actor' uses $'weapon_skill'.$'lb'$'target' gains the effect of $'status'.",
    195 :"$'target': TOTAL ALLIANCE SUM:$'number'/LEV:$'number'",
    196 :"Skillchain!$'lb'$'target' takes $'number' points of damage.",
    197 :"$'actor' uses $'weapon_skill', but $'target' resists.$'lb'$'target' takes $'number' points of damage.",
    198 :"$'target' is too far away.",
    199 :"That action requires a shield.",
    200 :"Time left until next use: ($'time')",
    201 :"Current time: ($'time')",
    202 :"Time left: ($'time')",
    203 :"$'target' is $'status'.",
    204 :"$'target' is no longer $'status'.",
    205 :"$'target' gains the effect of $'status'.",
    206 :"$'target''s $'status' effect wears off.",
    207 :"HP / HPMax:$'number'/$'number'",
    208 :"MP / MPMax:$'number'/$'number'",
    209 :"TP:$'number'%",
    210 :"$'actor' cannot charm $'target'!",
    211 :"It would be very difficult for $'actor' to charm $'target'.",
    212 :"It would be difficult for $'actor' to charm $'target'.",
    213 :"$'actor' might be able to charm $'target'.",
    214 :"$'actor' should be able to charm $'target'.",
    215 :"That action requires a pet.",
    216 :"You do not have a appropriate ranged weapon equipped.",
    217 :"You cannot see $'target'.",
    218 :"You move and interrupt your aim.",
    219 :"You cannot see $'target'.",
    220 :"You move and interrupt your aim.",
    221 :"$'actor' uses $'weapon_skill'.$'lb'$'target''s pet is released.",
    222 :"$'target' isn't selling anything.",
    223 :"Skillchain: $'number' points of damage.",
    224 :"$'actor' uses $'weapon_skill'.$'lb'$'target' recovers $'number' MP.",
    225 :"$'actor' uses $'weapon_skill'.$'lb'$'number' MP drained from $'target'.",
    226 :"$'actor' uses $'weapon_skill'.$'lb'$'number' TP drained from $'target'.",
    227 :"$'actor' casts $'spell'.$'lb'$'number' HP drained from $'target'.",
    228 :"$'actor' casts $'spell'.$'lb'$'number' MP drained from $'target'.",
    229 :"Additional effect: $'target' takes $'number' additional points of damage.",
    230 :"$'actor' casts $'spell'.$'lb'$'target' gains the effect of $'status'.",
    231 :"$'actor' uses $'weapon_skill'.$'lb'$'number' of $'target''s effects disappears!",
    232 :"$'target' is drawn in!",
    233 :"You are ineligible to attack that target.",
    234 :"Auto-targeting $'target'.",
    235 :"That is someone's pet.",
    236 :"$'actor' casts $'spell'.$'lb'$'target' is $'status'.",
    237 :"$'actor' casts $'spell'.$'lb'$'target' receives the effect of $'status'.",
    238 :"$'actor' uses $'weapon_skill'.$'lb'$'target' recovers $'number' HP.",
    239 :"Size: $'number'",
    240 :"$'actor' tries to hide, but is spotted by $'target'.",
    241 :"$'actor' hides!",
    242 :"$'actor' uses $'weapon_skill'.$'lb'$'target' is $'status'.",
    243 :"$'actor' uses $'weapon_skill'.$'lb'$'target' receives the effect of $'status'.",
    244 :"$'actor' fails to mug $'target'.",
    245 :"$'actor' uses Eagle Eye Shot, but misses $'target'.",
    246 :"$'target' is full.",
    247 :"$'actor' can't eat the $'item'.",
    248 :"$'actor''s attack has no effect on $'target'.",
    249 :"$'target''s strength is impossible to gauge!",
    250 :"Reraise takes effect!",
    251 :"The effect of $'status' is about to wear off.",
    252 :"$'actor' casts $'spell'.$'lb'Magic Burst!$'lb'$'target' takes $'number' points of damage.",
    253 :"EXP chain #$'number'!$'lb'$'actor' gains $'number' experience points.",
    254 :"Current enmity: $'number'",
    255 :"DEBUG: $'target''$'number'% chance of success.",
    256 :"In this flower pot: Seeds sown: $'item'",
    257 :"Crystal used: none",
    258 :"Crystal used: $'item'",
    259 :"First crystal used: $'item' Second crystal used: $'item'",
    260 :"First crystal used: none Second crystal used: $'item'",
    261 :"First crystal used: $'item' Second crystal used: none",
    262 :"First crystal used: none Second crystal used: none",
    263 :"$'target' recovers $'number' HP.",
    264 :"$'target' takes $'number' points of damage.",
    265 :"Magic Burst!$'lb'$'target' takes $'number' points of damage.",
    266 :"$'target' gains the effect of $'status'.",
    267 :"$'target' receives the effect of $'status'.",
    268 :"$'actor' casts $'spell'.$'lb'Magic Burst!$'lb'$'target' receives the effect of $'status'.",
    269 :"Magic Burst!$'lb'$'target' receives the effect of $'status'.",
    270 :"$'target' is $'status'.",
    271 :"$'actor' casts $'spell'.$'lb'Magic Burst!$'lb'$'target' is $'status'.",
    272 :"Magic Burst!$'lb'$'target' is $'status'.",
    273 :"$'target' vanishes!",
    274 :"$'actor' casts $'spell'.$'lb'Magic Burst!$'lb'$'number' HP drained from $'target'.",
    275 :"$'actor' casts $'spell'.$'lb'Magic Burst!$'lb'$'number' MP drained from $'target'.",
    276 :"$'target' recovers $'number' MP.",
    277 :"$'target' is $'status'.",
    278 :"$'target' receives the effect of $'status'.",
    279 :"$'target' is $'status'.",
    280 :"$'target' gains the effect of $'status'.",
    281 :"$'number' HP drained from $'target'.",
    282 :"$'target' evades.",
    283 :"No effect on $'target'.",
    284 :"$'target' resists the effects of the spell!",
    285 :"$'target''s attacks are enhanced.",
    286 :"$'target' is fortified against undead.",
    287 :"$'target' is fortified against arcana.",
    288 :"Skillchain: Light.$'lb'$'target' takes $'number' points of damage.",
    289 :"Skillchain: Darkness.$'lb'$'target' takes $'number' points of damage.",
    290 :"Skillchain: Gravitation.$'lb'$'target' takes $'number' points of damage.",
    291 :"Skillchain: Fragmentation.$'lb'$'target' takes $'number' points of damage.",
    292 :"Skillchain: Distortion.$'lb'$'target' takes $'number' points of damage.",
    293 :"Skillchain: Fusion.$'lb'$'target' takes $'number' points of damage.",
    294 :"Skillchain: Compression.$'lb'$'target' takes $'number' points of damage.",
    295 :"Skillchain: Liquefaction.$'lb'$'target' takes $'number' points of damage.",
    296 :"Skillchain: Induration.$'lb'$'target' takes $'number' points of damage.",
    297 :"Skillchain: Reverberation.$'lb'$'target' takes $'number' points of damage.",
    298 :"Skillchain: Transfixion.$'lb'$'target' takes $'number' points of damage.",
    299 :"Skillchain: Scission.$'lb'$'target' takes $'number' points of damage.",
    300 :"Skillchain: Detonation.$'lb'$'target' takes $'number' points of damage.",
    301 :"Skillchain: Impaction.$'lb'$'target' takes $'number' points of damage.",
    302 :"Skillchain: Cosmic Elucidation.$'lb'$'target' takes $'number' points of damage.",
    303 :"$'actor' uses Divine Seal.",
    304 :"$'actor' uses Elemental Seal.",
    305 :"$'actor' uses Trick Attack.",
    306 :"$'actor' uses $'ability'.$'lb'$'target' recovers $'number' HP.",
    307 :"That action requires a two-handed weapon.",
    308 :"Unable to use the $'item'.$'lb'$'target''s inventory is full.",
    309 :"$'actor' casts $'spell' on $'target'.",
    310 :"$'actor''s $'skill' skill drops 0.$'number' points!",
    311 :"$'actor' covers $'target'.",
    312 :"$'actor''s attempt to cover has no effect.",
    313 :"$'target' is out of range.$'lb'Unable to cast $'spell'.",
    314 :"$'target''s level is currently restricted to $'number'.$'lb'Equipment affected by the level restriction will be adjusted accordingly.",
    315 :"$'actor' already has a pet.",
    316 :"That action cannot be used in this area.",
    317 :"$'actor' uses $'ability'.$'lb'$'target' takes $'number' points of damage.",
    318 :"$'actor' uses $'ability'.$'lb'$'target' recovers $'number' HP.",
    319 :"$'actor' uses $'ability'.$'lb'$'target' gains the effect of $'status'.",
    320 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of $'status'.",
    321 :"$'actor' uses $'ability'.$'lb'$'target''s $'status' .",
    322 :"$'actor' uses $'ability'.$'lb'$'target''s $'status' effect wears off.",
    323 :"$'actor' uses $'ability'.$'lb'No effect on $'target'.",
    324 :"$'actor' uses $'ability', but misses $'target'.",
    325 :"You are charmed by a enemy and unable to act.",
    326 :"$'actor' readies $'ability'.",
    327 :"$'actor' starts casting $'spell' on $'target'.",
    328 :"$'target' is too far away.",
    329 :"$'actor' casts $'spell'.$'lb'$'target''s STR is drained.",
    330 :"$'actor' casts $'spell'.$'lb'$'target''s DEX is drained.",
    331 :"$'actor' casts $'spell'.$'lb'$'target''s VIT is drained.",
    332 :"$'actor' casts $'spell'.$'lb'$'target''s AGI is drained.",
    333 :"$'actor' casts $'spell'.$'lb'$'target''s INT is drained.",
    334 :"$'actor' casts $'spell'.$'lb'$'target''s MND is drained.",
    335 :"$'actor' casts $'spell'.$'lb'$'target''s CHR is drained.",
    336 :"No effect on that pet.",
    337 :"You do not have the necessary item equipped to call a beast.",
    338 :"You cannot summon avatars here.",
    339 :"Your chocobo senses a hostile presence and refuses to come to your side.",
    340 :"You must equip your main weapon first to use Dual Wield.",
    341 :"$'actor' casts $'spell'.$'lb'$'target''s $'status' effect disappears!",
    342 :"$'actor' casts $'spell'.$'lb'$'target''s $'status' effect disappears!",
    343 :"$'target''s $'status' effect disappears!",
    344 :"$'target''s $'status' effect disappears!",
    345 :"You cannot heal while you have a avatar summoned.",
    346 :"You must summon a avatar to use that command.",
    347 :"You must have pet food equipped to use that command.",
    348 :"You cannot call wyverns here.",
    349 :"You cannot call beasts here.",
    350 :"$'target' is no longer $'status'.",
    351 :"The remedy removes $'target''s status ailments.",
    352 :"$'actor''s ranged attack hits $'target' for $'number' points of damage.",
    353 :"$'actor''s ranged attack scores a critical hit!$'lb'$'target' takes $'number' points of damage.",
    354 :"$'actor''s ranged attack misses.",
    355 :"$'actor''s ranged attack has no effect on $'target'.",
    356 :"Cannot execute command.$'lb'Your inventory is full.",
    357 :"$'target' regains $'number' HP.",
    358 :"$'target' regains $'number' MP.",
    359 :"$'target' narrowly escapes impending doom.",
    360 :"$'actor' uses $'weapon_skill'.$'lb'All of $'target''s abilities are recharged.",
    361 :"All of $'target''s abilities are recharged.",
    362 :"$'actor' uses $'weapon_skill'.$'lb'$'target''s TP is reduced to $'number'.",
    363 :"$'target''s TP is reduced to $'number'.",
    364 :"$'actor' uses $'ability'.$'lb'All of $'target''s status parameters are boosted.",
    365 :"All of $'target''s status parameters are boosted.",
    366 :"$'number' MP drained from $'target'.",
    367 :"$'target' recovers $'number' HP.",
    368 :"$'actor' earns a merit points!$'lb'(Total: $'number')",
    369 :"$'actor' uses $'weapon_skill'.$'lb'$'number' of $'target''s attributes is drained.",
    370 :"$'actor' uses $'weapon_skill'.$'lb'$'number' status effect is drained from $'target'.",
    371 :"$'actor' gains $'number' limit points.",
    372 :"Limit chain #$'number'!$'lb'$'actor' gains $'number' limit points.",
    373 :"$'actor' hits $'target'.$'lb'$'target' recovers $'number' hit points!",
    374 :"Striking $'target''s armor causes $'actor' to become $'status'.",
    375 :"$'actor' uses a $'item'.$'lb'$'target' receives the effect of $'status'.",
    376 :"$'actor' uses a $'item'.$'lb'$'target' obtains a $'item2'.",
    377 :"$'actor' uses a $'item'.$'lb'$'target' obtains $'item2'.",
    378 :"$'actor' uses a $'item'.$'lb'$'target''s $'status' effect disappears!",
    379 :"$'actor' uses $'ability'.$'lb'Magic Burst!$'lb'$'target' takes $'number' points of damage.",
    380 :"$'merit skill' modification has risen to level $'number'.",
    381 :"$'merit skill' modification has dropped to level $'number'.",
    382 :"$'actor''s ranged attack hits $'target'.$'lb'$'target' recovers $'number' hit points!",
    383 :"$'target''s spikes restore $'number' HP to $'actor'.",
    384 :"Additional effect: $'target' recovers $'number' HP.",
    385 :"Skillchain: Light.$'lb'$'target' recovers $'number' hit points!",
    386 :"Skillchain: Darkness.$'lb'$'target' recovers $'number' hit points!",
    387 :"Skillchain: Gravitation.$'lb'$'target' recovers $'number' hit points!",
    388 :"Skillchain: Fragmentation.$'lb'$'target' recovers $'number' hit points!",
    389 :"Skillchain: Distortion.$'lb'$'target' recovers $'number' hit points!",
    390 :"Skillchain: Fusion.$'lb'$'target' recovers $'number' hit points!",
    391 :"Skillchain: Compression.$'lb'$'target' recovers $'number' hit points!",
    392 :"Skillchain: Liquefaction.$'lb'$'target' recovers $'number' hit points!",
    393 :"Skillchain: Induration.$'lb'$'target' recovers $'number' hit points!",
    394 :"Skillchain: Reverberation.$'lb'$'target' recovers $'number' hit points!",
    395 :"Skillchain: Transfixion.$'lb'$'target' recovers $'number' hit points!",
    396 :"Skillchain: Scission.$'lb'$'target' recovers $'number' hit points!",
    397 :"Skillchain: Detonation.$'lb'$'target' recovers $'number' hit points!",
    398 :"Skillchain: Impaction.$'lb'$'target' recovers $'number' hit points!",
    399 :"$'actor' uses a $'item'.$'lb'All of $'target''s Petras vanish!",
    400 :"$'actor' uses a $'item'.$'lb'$'number' of $'target''s status ailments disappears!",
    401 :"$'actor' uses a $'item'.$'lb'$'number' of $'target''s effects disappears!",
    402 :"$'actor' uses $'weapon_skill'.$'lb'$'target''s magic defense is enhanced.",
    403 :"$'number' of $'target''s attributes is drained.",
    404 :"$'number' status effect is drained from $'target'.",
    405 :"$'actor' uses $'weapon_skill'.$'lb'$'number' of $'target''s effects disappears!",
    406 :"$'actor' uses $'weapon_skill'.$'lb'$'target' falls to the ground.",
    407 :"$'actor' uses a $'item'.$'lb'$'target''s TP is reduced.",
    408 :"$'actor' uses a $'item'.$'lb'No effect on $'target'.",
    409 :"$'actor' uses $'weapon_skill'.$'lb'$'target''s TP is increased to $'number'.",
    410 :"No target available.$'lb'Unable to use item.",
    411 :"$'actor' attempts to use the $'item', but lacks the required number of Ballista Points.$'lb'You currently have $'number' Ballista points.",
    412 :"$'actor' uses a $'item'.$'lb'$'target' receives the effect of $'status'.",
    413 :"$'actor' uses a $'item'.$'lb'$'target' takes $'number' points of damage.",
    414 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Magic Attack Boost and Magic Defense Boost.",
    415 :"$'target' receives the effect of Magic Attack Boost and Magic Defense Boost.",
    416 :"$'actor' uses $'weapon_skill'.$'lb'$'target' receives the effect of Magic Attack Boost and Magic Defense Boost.",
    417 :"$'actor' uses $'ability'.$'lb'$'number' of $'target''s attributes is drained.",
    418 :"$'actor' uses $'weapon_skill' on $'target'.$'lb'$'target''s target switches to $'actor'!",
    419 :"$'target' learns $'spell'!",
    420 :"$'actor' uses $'ability'. The total comes to $'number'!$'lb'$'target' receives the effect of $'ability'.",
    421 :"$'target' receives the effect of $'ability'.",
    422 :"$'actor' uses $'ability'.$'lb'The total comes to $'number'!$'lb'No effect on $'target'.",
    423 :"No effect on $'target'.",
    424 :"$'actor' uses Double-Up.$'lb'The total for $'ability' increases to $'number'!$'lb'$'target' receives the effect of $'ability'.",
    425 :"$'actor' uses Double-Up.$'lb'The total for $'ability' increases to $'number'!$'lb'No effect on $'target'.",
    426 :"$'actor' uses Double-Up.$'lb'Bust!$'lb'$'target' loses the effect of $'ability'.",
    427 :"$'target' loses the effect of $'ability'.",
    428 :"There are no rolls eligible for Double-Up.$'lb'Unable to use ability.",
    429 :"The same roll is already active on $'actor'.",
    430 :"$'actor' casts $'spell'.$'lb'1 of $'target''s attributes is drained.",
    431 :"$'actor' casts $'spell'.$'lb'$'target''s TP is reduced.",
    432 :"$'actor' casts $'spell'.$'lb'$'target' receives the effect of Accuracy Boost and Evasion Boost.",
    433 :"$'actor' casts $'spell'.$'lb'$'target' receives the effect of Magic Attack Boost and Magic Defense Boost.",
    434 :"You cannot customize an activated automaton.",
    435 :"$'actor' uses $'ability'!$'lb'$'target''s abilities are recharged.",
    436 :"$'target''s abilities are recharged.",
    437 :"$'actor' uses $'ability'!$'lb'$'target''s abilities are recharged.$'lb'$'target''s TP is increased.",
    438 :"$'target''s abilities are recharged.$'lb'$'target''s TP is increased.",
    439 :"$'actor' uses $'ability'!$'lb'All of $'target''s abilities are recharged.$'lb'$'target' regains MP.",
    440 :"All of $'target''s abilities are recharged.$'lb'$'target' regains MP.",
    441 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of $'ability'.",
    442 :"$'actor' learns a new ability!",
    443 :"You cannot learn $'ability'.$'lb'You do not meet the job or level requirements.",
    444 :"You already know $'ability'.",
    445 :"You cannot use items at this time.",
    446 :"You cannot attack that target.",
    447 :"You are provoked and unable to change your target.",
    448 :"Time allowed in Dynamis has been extended by $'number' minute.",
    449 :"---:: WARNING ::---- Time remaining in Dynamis: $'number' minute.",
    450 :"WATCH$'number' $'target':$'number'",
    451 :"$'actor' uses $'ability'.$'lb'$'target' regains $'number' MP.",
    452 :"$'actor' uses $'ability'.$'lb'$'target' regains $'number' TP.",
    453 :"$'actor' uses $'ability'.$'lb'$'actor' steals the effect of $'status' from $'target'.",
    454 :"$'actor' casts $'spell'.$'lb'$'number' TP drained from $'target'.",
    455 :"Debug : Fishing skill check: $'item' : ???$'number'",
    456 :"Debug : Level Restriction on.$'lb'PetType $'number'/ID $'number'",
    457 :"Debug : Level restriction off.$'lb'PetType $'number'/ID $'number'",
    458 :"Debug : Dif - Now ' $'number' RATE $'number'/10",
    459 :"Self-destruct check: skipping calculation of $'target''s self-destruct process md_no$'number'/cmd_arg$'number'!",
    460 :"EXP Check: $'actor' ' $'target' XP:$'number'/LvUp$'number'",
    461 :"$'target':STR $'number'/$'number'",
    462 :"$'target':DEX $'number'/$'number'",
    463 :"$'target':VIT $'number'/$'number'",
    464 :"$'target':AGI $'number'/$'number'",
    465 :"$'target':INT $'number'/$'number'",
    466 :"$'target':MND $'number'/$'number'",
    467 :"$'target':CHR $'number'/$'number'",
    468 :"Wyvern: JobLv$'$'number'' TaskLv$'$'number''",
    469 :"ID: Master$'$'number'' Pet$'$'number''",
    470 :"Wyvern routine type: Master$'$'number'' Pet$'$'number''",
    471 :"Avatar type: Master$'$'number'' Pet$'$'number''",
    472 :"Avatar MP: Master$'$'number'' Pet$'$'number''",
    473 :"Avatar HP: Master$'$'number'' Pet$'$'number''",
    474 :"Avatar level: Master$'$'number'' Pet$'$'number''",
    475 :"Avatar No.: Master$'$'number'' Pet$'$'number''",
    476 :"Probability of $'target' dropping $'item': $'number'/10",
    477 :"Unable to target $'target'.$'lb'You have not received the level cap status.",
    478 :"Height differential between $'actor' and $'target': $'number'mm.",
    479 :"Damage taken.",
    480 :"Number of Targets ($'number') Damage ($'number')",
    481 :"Overall: Number of Attacks ($'number') Misses ($'number')",
    482 :"Number of Targets ($'number') Damage ($'number')",
    483 :"Ranged Attack: Number of Attacks ($'number') Misses ($'number')",
    484 :"Number of Targets ($'number') Damage ($'number')",
    485 :"JA: Number of Attacks ($'number') Misses ($'number')",
    486 :"Number of Targets ($'number') Damage ($'number')",
    487 :"Weapon Skill: Number of Attacks ($'number') Misses ($'number')",
    488 :"Number of Targets ($'number') Damage($'number')",
    489 :"Spell: Number of Attacks ($'number') Misses ($'number')",
    490 :"Number of Targets ($'number') Damage($'number')",
    491 :"AA: Number of Attacks ($'number') Misses ($'number')",
    492 :"Time: $'number'",
    493 :"$'actor''s log",
    494 :"??????:$'number' ??????:$'number'",
    495 :"$'actor'???:$'skill''????$'number'%",
    496 :"$'actor'???:$'skill''?????$'number'%",
    497 :"??????$'actor' : ??+$'number'/??+$'number'%",
    498 :"????? $'actor' ' $'target'",
    499 :"Hate : $'actor''$'target' $'number'/$'number'",
    500 :"????to?? $'actor':CODE $'number'/$'number'",
    501 :"StatusGet($'target':$'number'/$'number')",
    502 :"StatusSet($'target':$'number'/$'number')",
    503 :"$'target': Skillchain Element $'number'($'number')",
    504 :"$'target':???????????($'number'?????$'number'%)",
    505 :"$'target':????????($'number')???????($'number')?",
    506 :"$'target':????????($'number')???????($'number')?",
    507 :"$'target':??????????:$'number'/?????????:$'number'",
    508 :"$'target':??????$'number'%,PS$'number'",
    509 :"$'target':$' $'number'/$'number' '",
    510 :"DEBUG:$'target''$'skill' : $'number'%",
    511 :"DEBUG:$'target''$'number'%?????($'number')?",
    512 :"You must have a two-handed weapon equipped in the main weapon slot in order to equip a grip.",
    513 :"This grip is not compatible with the two-handed weapon you currently have equipped.",
    514 :"You do not have the proper items equipped to use the $'item'.",
    515 :"$'actor' has successfully recorded the target's image onto a $'item'.",
    516 :"$'actor' was unable to capture the target's image.",
    517 :"The $'item' cannot be used on that target.",
    518 :"The $'item' cannot be used while under the effect of Invisible or Sneak.",
    519 :"$'actor' uses $'ability'.$'lb'$'target' is afflicted with Lethargic Daze (lv.$'number').",
    520 :"$'actor' uses $'ability'.$'lb'$'target' is afflicted with Sluggish Daze (lv.$'number').",
    521 :"$'actor' uses $'ability'.$'lb'$'target' is afflicted with Weakened Daze (lv.$'number').",
    522 :"$'actor' uses $'ability'.$'lb'$'target' takes $'number' points of damage and is stunned.",
    523 :"The same effect is already active on $'actor'.",
    524 :"You have not earned enough finishing moves to perform that action.",
    525 :"$'ability' can only be performed during battle.",
    526 :"$'actor' uses $'ability'.$'lb'Enmity is stolen from $'target'.",
    527 :"$'actor' uses $'ability'.$'lb'Ranged attack power and speed are increased.$'lb'Melee attack power and speed are reduced.",
    528 :"$'actor' uses $'ability'.$'lb'Enmity is transferred to $'actor''s pet.",
    529 :"$'actor' uses $'ability'.$'lb'$'target' is chainbound.",
    530 :"$'target''s petrification counter is now down to $'number'.",
    531 :"$'target' is no longer $'status'.",
    532 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Sneak and Invisible.",
    533 :"$'actor' casts $'spell'.$'lb'$'target''s Accuracy is drained.",
    534 :"$'actor' casts $'spell'.$'lb'$'target''s Attack is drained.",
    535 :"$'target' retaliates.$'lb'$'number' of $'actor''s shadows absorbs the damage and disappears.",
    536 :"$'target' retaliates.$'lb'$'actor' takes $'number' points of damage.",
    537 :"$'target''s TP is increased to $'number'%.",
    538 :"A protective energy absorbs the malice of your enemy!",
    539 :"$'actor' uses $'weapon_skill'.$'lb'$'target' regains HP.",
    540 :"Level Sync activated.$'lb'Your level has been restricted to $'number'.$'lb'Equipment affected by the level restriction will be adjusted accordingly.$'lb'Experience points will become unavailable for all party members should the Level Sync designee stray too far from the enemy.",
    541 :"Level Sync could not be activated.$'lb'The designated player is below level 10.",
    542 :"Level Sync could not be activated.$'lb'The designated player is in a different area.",
    543 :"Level Sync could not be activated.$'lb'One or more party members are currently under the effect of a status which prevents synchronization.",
    544 :"Level synchronization will be removed in $'number' seconds.",
    545 :"No experience points gained...$'lb'The Level Sync designee is either too far from the enemy, or unconscious.",
    546 :"Your $'status' effect duration has been extended.",
    547 :"This ability can only be used on targets under the effect of a helix.",
    548 :"The party member you have selected is incapable of receiving experience points, and as such cannot be a Level Sync designee.",
    549 :"No experience points gained...$'lb'The Level Sync designee is incapable of receiving experience points.",
    550 :"Level Sync will be deactivated in $'number' seconds.$'lb'One or more party members have received the effect of a status which prevents synchronization.",
    551 :"Level Sync will be deactivated in $'number' seconds.$'lb'The party leader or the Level Sync designee has left the area.",
    552 :"Level Sync will be deactivated in $'number' seconds.$'lb'Less than two party members fulfill the requirements for Level Sync.",
    553 :"Level Sync will be deactivated in $'number' seconds.$'lb'The party leader has removed synchronization, or the Level Sync designee has left the party.",
    554 :"Level Sync will be deactivated in $'number' seconds.$'lb'The Level Sync designee has fallen below level 10.",
    555 :"Level Sync will be deactivated in $'number' seconds.$'lb'A party member has undergone a job change.",
    556 :"Level Sync will be deactivated in $'number' seconds.$'lb'The Level Sync designee is incapable of receiving experience points.",
    557 :"$'target' receives $'number' piece of alexandrite.",
    558 :"You defeated a designated target.$'lb'(Progress: $'number'/$'number2')",
    559 :"You have successfully completed the training regime.",
    560 :"$'actor' uses $'ability'. Finishing move now $'number'.",
    561 :"Unable to perform that action.$'lb'Your have already earned the maximum number of finishing moves.",
    562 :"The status parameters of $'target' have increased.",
    563 :"$'actor' destroys $'target'.",
    564 :"$'target' were destroyed.",
    565 :"$'target' obtains $'gil'.",
    566 :"$'target' obtains $'number' tab.$'lb'(Total: $'number')",
    567 :"$'actor' stowed away a $'item' in ?Unknown Parameter (Type: 90) 91?his/her tattered Maze Monger pouch.",
    568 :"Your tattered Maze Monger pouch already contains a $'item' and cannot hold another.",
    569 :"Your current status prevents you from using that ability.",
    570 :"$'actor' casts $'spell'.$'lb'$'number' of $'target''s status ailments disappears!",
    571 :"$'number' of $'target''s status ailments disappears!",
    572 :"$'actor' casts $'spell'.$'lb'$'actor' absorbs $'number' of $'target''s status ailments.",
    573 :"$'actor' or a alliance member is participating in a union.$'lb'Ineligible to obtain treasure from this enemy.",
    574 :"$'actor''s pet is currently unable to perform that action.",
    575 :"$'actor''s pet does not have enough TP to perform that action.",
    576 :"$'actor''s ranged attack hits $'target' squarely for $'number' points of damage!",
    577 :"$'actor''s ranged attack strikes true, pummeling $'target' for $'number' points of damage!",
    578 :"Hunt objective fulfilled!$'lb'Please report to a hunt registry to collect your reward.",
    579 :"Unable to use the $'item'.$'lb'Party leaders or those not in a party cannot use a $'item'.",
    580 :"Unable to use the $'item'.$'lb'The party leader is in either a area beyond warping range or a place you have yet to visit.",
    581 :"Unable to cast $'spell'.$'lb'Astral Flow must be in effect to cast this spell.",
    582 :"$'actor' obtains $'gil'.",
    583 :"Trial $'number': $'number' objective remains.",
    584 :"You have completed Trial $'number'.$'lb'Report your success to a Magian Moogle.",
    585 :"$'actor' uses $'ability'.$'lb'$'target''s enmity towards $'actor' is $'number'%.",
    586 :"Towards $'target' is $'number'%.",
    587 :"$'target' regains $'number' HP.",
    588 :"$'target' regains $'number' MP.",
    589 :"$'target' have been healed of $'number' status ailments.",
    590 :"You can now perform $'weapon_skill'.",
    591 :"$'actor' uses $'ability'.$'lb'$'target' is afflicted with Bewildered Daze (lv.$'number').",
    592 :"$'target' attempts to counter $'actor''s attack, but misses.",
    593 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Attack Down.",
    594 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Defense Down.",
    595 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Magic Atk. Down.",
    596 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Magic Def. Down.",
    597 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Evasion Down.",
    598 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Accuracy Down.",
    599 :"$'actor' uses $'ability'.$'lb'$'actor' steals a $'item' from $'target'.$'lb'Additional effect: $'target' is afflicted with Slow.",
    600 :"$'actor' eats a $'item'.$'lb'$'actor' finds a $'item2' inside!",
    601 :"Objective fulfilled!$'lb'Please report to a Dominion Sergeant to collect your reward.",
    602 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of $'ability'.",
    603 :"Additional effect: Treasure Hunter effectiveness against $'target' increases to $'number'.",
    604 :"$'actor' eats a $'item', but finds nothing inside...",
    605 :"Additional effect: $'target' falls to the ground.",
    606 :"$'actor''s absorbs $'target''s counter.$'lb'$'actor' recovers $'number' HP.",
    607 :"$'actor' uses $'weapon_skill'.$'lb'$'number' of $'target''s status ailments disappears!",
    608 :"$'actor' uses $'ability'.$'lb'Treasure Hunter effectiveness against $'target' increases to $'number'.",
    609 :"Prowess attained: Increased treasure casket discovery.",
    610 :"Prowess attained: Increased combat and magic skill gain.",
    611 :"Prowess attained: Increased crystal yield.",
    612 :"Prowess attained: Treasure Hunter bonus.",
    613 :"Prowess attained: Increased attack speed.",
    614 :"Prowess attained: Increased HP and MP.",
    615 :"Prowess attained: Enhanced accuracy and ranged accuracy.",
    616 :"Prowess attained: Enhanced attack and ranged attack.",
    617 :"Prowess attained: Enhanced magic accuracy and magic attack.",
    618 :"Prowess attained: Enhanced \"Cure\" potency.",
    619 :"Prowess attained: Increased weapon skill damage.",
    620 :"Prowess attained: \"Killer\" effects bonus.",
    625 :"Prowess boosted: Increased treasure casket discovery.",
    626 :"Prowess boosted: Increased combat and magic skill gain.",
    627 :"Prowess boosted: Increased crystal yield.",
    628 :"Prowess boosted: Treasure Hunter bonus.",
    629 :"Prowess boosted: Increased attack speed.",
    630 :"Prowess boosted: Increased HP and MP.",
    631 :"Prowess boosted: Enhanced accuracy and ranged accuracy.",
    632 :"Prowess boosted: Enhanced attack and ranged attack.",
    633 :"Prowess boosted: Enhanced magic accuracy and magic attack.",
    634 :"Prowess boosted: Enhanced \"Cure\" potency.",
    635 :"Prowess boosted: Increased weapon skill damage.",
    636 :"Prowess boosted: \"Killer\" effects bonus.",
    641 :"Additional effect: 1 of $'target''s attributes is drained.",
    642 :"$'actor' casts $'spell'.$'lb'$'actor' absorbs $'number' of $'target''s status benefits.",
    643 :"Your current training regime will begin anew!",
    644 :"$'actor' uses $'ability'.$'lb'$'number' of $'target''s status effects are removed.",
    645 :"$'actor' uses $'ability'.$'lb'$'target' is $'status'.",
    646 :"$'actor' uses $'ability'.$'lb'$'target' falls to the ground.",
    647 :"$'actor' casts $'ability'.$'lb'$'target''s $'status' effect disappears!",
    648 :"$'actor' leads the casting of $'spell'.$'lb'$'target' takes $'number' points of damage.",
    649 :"A member of another party is readying $'spell' against your target.$'lb'You cannot cast the same spell at this time.",
    650 :"$'actor' leads the casting of $'spell'.$'lb'Magic Burst!$'lb'$'target' takes $'number' points of damage.",
    651 :"$'actor' leads the casting of $'spell'.$'lb'$'target' recovers $'number' hit points!",
    652 :"Additional effect: $'target' loses $'number' TP.",
    653 :"$'actor' casts $'spell'.$'lb'$'target' resists the spell.$'lb'Immunobreak!",
    654 :"$'target' resists the spell.$'lb'Immunobreak!",
    655 :"$'actor' casts $'spell'.$'lb'$'target' completely resists the spell.",
    656 :"$'target' completely resists the spell.",
    657 :"$'actor' uses $'ability'.$'lb'All enmity is transferred to $'target'.",
    658 :"$'actor' uses $'ability', but misses $'target'.",
    659 :"No effect on $'target'.",
    660 :"The same effect is already active on that luopan!",
    661 :"$'actor' has already placed a luopan.$'lb'Unable to use ability.",
    662 :"This action requires a luopan.",
    663 :"$'actor' uses $'ability'.$'lb'The luopan's HP consumption rate has been reduced.",
    664 :"$'actor' uses $'ability'.$'lb'The effects of the luopan and its HP consumption rate have increased.",
    665 :"$'actor' has a pet.$'lb'Unable to use ability.",
    666 :"This action requires the ability Rune Enchantment.",
    667 :"$'actor' uses $'ability'.$'lb'Accuracy and evasion are enhanced.",
    668 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Vallation, reducing damage taken from certain elemental magic spells.",
    669 :"Magic damage of a certain element is reduced for $'target'.",
    670 :"$'actor' uses $'ability'.$'lb'$'target' can now absorb magic damage of a certain element.",
    671 :"$'actor' uses $'ability'.$'lb'$'target' now has enhanced resistance.",
    672 :"$'actor' uses $'ability'.$'lb'$'target' receives the effect of Gambit, reducing defense against magic of a certain element.",
    673 :"$'actor' obtains $'number' corpuscles of menace plasm.",
    674 :"$'actor' uses $'ability', and finds $'number' $'item2'.",
    675 :"$'actor' readies $'weapon_skill'.",
    676 :"$'target''s movement speed increases.",
    677 :"You are now able to shapeshift into a new monster!",
    678 :"You have learned a new instinct!",
    679 :"$'actor' will return to the Feretory in: $'number2'.",
    680 :"A newfound puissance courses through your veins.",
    681 :"Your muscles ripple with an immensely powerful and invigorating force.",
    682 :"Your puissance withers slightly.",
    683 :"You have claimed $'target'!",
    684 :"$'target' has been claimed!",
    685 :"The enemy you are battling will no longer be claimed in: $'number'.",
    686 :"The enemy you were battling is no longer claimed.",
    687 :"$'actor' captured the $'target'.",
    688 :"$'actor' has fled!",
    689 :"$'actor' captured the $'target'.",
    690 :"You have completed the following Records of Eminence objective: $'regime'.",
    691 :"This objective may be repeated, and can be canceled from the menu.",
    692 :"You receive $'number' sparks of eminence and now possess a total of $'number2'.",
    693 :"As a special bonus for your valiant efforts, you have been awarded $'item'.",
    694 :"As a special bonus for your valiant efforts, you have been awarded $'number' sparks of eminence.",
    695 :"Unable to receive special bonus. Make room in your inventory and receive your reward from the Records of Eminence menu.",
    696 :"You have yet to receive certain special bonuses from objectives you have completed. Make room in your inventory and receive your rewards from the Records of Eminence menu.",
    697 :"Records of Eminence: $'regime'.",
    698 :"Progress: $'number'/$'number2'.",
    699 :"A new objective has been added!",
    700 :"You are unable to use Trust magic at this time.",
    701 :"There's no time to do that now!",
    704 :"You have undertaken \"$'regime'.\"",
    705 :"You have undertaken the limited-time Records of Eminence challenge \"$'regime'.\".",
    706 :"You have obtained a $'item' as a special reward.",
    707 :"As a first-time bonus, you receive $'number' sparks of eminence for a total of $'number2'!",
    708 :"This place is now known as a location that brings memories flooding back to $'actor'.",
    709 :"As a special bonus for your valiant efforts, you have been awarded the following: $'item'",
    710 :"You are cleared to fulfill this objective again.",
    711 :"($'actor') $'item'",
    712 :"Primary Accuracy: $'number' / Primary Attack: $'number2'",
    713 :"Auxiliary Accuracy: $'number' / Auxiliary Attack: $'number2'",
    714 :"Ranged Accuracy: $'number' / Ranged Attack: $'number2'",
    715 :"Evasion: $'number' / Defense: $'number2'",
    716 :"$'actor' starts casting $'spell'.",
    717 :"You cannot call forth alter egos here.",
    718 :"$'actor' gains $'number' capacity points.",
    719 :"$'actor' earns a job point!",
    720 :"Your $'job_point_skill' modification has risen to level $'number'",
    721 :"You receive a bonus of $'number' fishing guild points!",
    722 :"You receive a bonus of $'number' woodworking guild points!",
    723 :"You receive a bonus of $'number' smithing guild points!",
    724 :"You receive a bonus of $'number' goldsmithing guild points!",
    725 :"You receive a bonus of $'number' clothcraft guild points!",
    726 :"You receive a bonus of $'number' leathercraft guild points!",
    727 :"You receive a bonus of $'number' bonecraft guild points!",
    728 :"You receive a bonus of $'number' alchemy guild points!",
    729 :"You receive a bonus of $'number' cooking guild points!",
    730 :"$'actor' uses $'ability'$'lb'$'target''s TP is reduced to $'number'.",
    731 :"Average item level: $'number'.",
    732 :"Skillchain: Universal Enlightenment.$'lb'$'target' takes $'number' points of damage",
    733 :"$'target':",
    734 :"$'actor' uses $'ability' on $'target'.",
    735 :"Capacity chain #$'number'!$'lb'$'actor' gains $'number2' capacity points.",
    736 :"$'actor' uses $'ability'.$'lb'$'number' HP drained from $'target'.",
    737 :"$'actor' uses $'ability'. $'lb'$'number' of $'target' magic effects is drained.",
    738 :"$'actor' uses $'ability'.",
    739 :"$'target' receives $'number' magical effects.",
    740 :"$'target': $lt; $'number'/$'number2'",
    741 :"You receive $'number' Unity accolades for a total of $'number2'!",
    742 :"You are currently unable to undertake this objective.",
    743 :"$'actor' uses $'ability'.$'lb'$'target''s enmity decreases.",
    744 :"$'actor'奄",
    745 :"Your automaton exceeds one or more elemental capacity values and cannot be activated.",
    746 :"$'actor' uses $'ability'.$'lb'$'number' TP drained from $'target'.",
    747 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'target' takes $'number' points of damage.",
    748 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'number' HP drained from $'target'.",
    749 :"Magic Burst! $'number' HP drained from $'target'.",
    750 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'number' MP drained from $'target'.",
    751 :"Magic Burst! $'number' MP drained from $'target'.",
    752 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'number' TP drained from $'target'.",
    753 :"Magic Burst! $'number' TP drained from $'target'.",
    754 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'target' is $'status'.",
    755 :"$'actor' uses $'spell'.$'lb'Magic Burst! $'target' receives the effect of $'status'.",
    756 :"$'target''s spikes cause $'target' to fall to the ground.",
    757 :"$'number' of $'target''s effects disappears!",
    758 :"$'actor' uses $'item'.$'lb'→Obtained key item: $'key_item'.",
    759 :"You already have key item: $'key_item'.",
    760 :"You are only able to possess one $'item' and thus are unable to receive your just reward. Clear out your inventory and receive the item from the Records of Eminence Menu.",
    761 :"You were unable to receive your just reward because you need $'number' free spaces in your inventory. Clear out your bags and receive your item from the Records of Eminence Menu.",
    762 :"$'actor' uses $'spell'.$'lb'All of $'target''s status parameters are boosted.",
    763 :"$'actor' uses $'spell'.$'lb'$'target' has grown noticeably bored.",
    764 :"$'actor' uses $'spell'.$'lb'$'target' feels the Fever!",
    765 :"$'actor' uses $'item'.$'lb'$'target' obtains $'number' escha silt.",
    766 :"$'actor' uses $'item'.$'lb'$'target' obtains $'number' escha beads.",
    767 :"Skillchain: Radiance.$'lb'$'target' takes $'number' points of damage.",
    768 :"Skillchain: Umbra.$'lb'$'target' takes $'number' points of damage.",
    769 :"Skillchain: Radiance.$'lb'$'target' recovers $'number' hit points!",
    770 :"Skillchain: Umbra.$'lb'$'target' recovers $'number' hit points!",
    771 :"Congratulations! Your deeds of valor will ring throughout the ages, providing inspiration for generations to come.",
    772 :"$'actor' stands resolute thanks to the power of the bonds that tie you!",
    773 :"You are unable to call forth your mount because your main job level is not at least ≺Possible Special Code: 12≻≺Possible Special Code: 00≻.",
    774 :"You already possess that item and are unable to receive your just reward!",
    775 :"A new objective has been added in the Contents > Content (Ambuscade) Records of Eminence category!",
    776 :"Additional effect: $'target' is chainbound.",
    777 :"You cannot mount at this time.",
    778 :"$'actor' uses $'ability'.$'lb'$'actor' copies $'number' magical effects from $'target'.",
    779 :"$'actor' uses $'ability'.$'lb'A barrier begins to pulsate around $'target'.",
    780 :"$'actor' uses $'ability'.$'lb'$'actor' takes aim at $'target'!",
    781 :"$'target' retaliates, absorbing $'number' TP from $'actor'.",
}

# lua to python



